version: '2'

services:

  kbs-tempus:
    build: .
    volumes:
      - .:/usr/share/nginx/www
    expose:
      - 8001
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - kbs-db

  kbs-db:
    image: mysql:latest
    container_name: kbs_db
    expose:
      - 3306
    ports:
      - "3307:3306"
    env_file:
      - ./db-local/conf/db-config.ini