<?php

namespace AppBundle\Repository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{

    public function createFindOneByIdQuery(int $id)
    {
        $query = $this->_em->createQuery(
            "
            SELECT app
            FROM AppBundle:Application app
            WHERE app.id = :id
            "
        );

        $query->setParameter('id', $id);

        return $query;
    }


    public function createFindAllQuery()
    {
        return $this->_em->createQuery(
            "
            SELECT app
            FROM AppBundle:Application app
            "
        );
    }
}
