<?php

namespace AppBundle\Repository;


/**
 * EquipmentTypeRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class EquipmentTypeRepository extends AbstractRepository
{
}
