<?php

namespace AppBundle\Repository;


/**
 * InstitutionRiskLevelRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class InstitutionRiskLevelRepository extends AbstractRepository
{
}
