<?php

namespace AppBundle\Repository;


/**
 * ProjectEquipmentRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ProjectEquipmentRepository extends AbstractRepository
{
}
