<?php

namespace AppBundle\Repository;

/**
 * ProjectsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectsRepository extends \Doctrine\ORM\EntityRepository
{
    public function saveProject($project) {

        $this->_em->persist($project);
        $this->_em->flush();
    }

}
