<?php

namespace AppBundle\Repository;


/**
 * RiskLevelTypeRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class RiskLevelTypeRepository extends AbstractRepository
{
}
