<?php

namespace AppBundle\Repository;


/**
 * RiskLevelManuallyUploadedRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class RiskLevelManuallyUploadedRepository extends AbstractRepository
{
}
