app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{locale}
_translation_webui:
    resource: "@TranslationBundle/Resources/config/routing_webui.yml"
    prefix:  /admin/f649f4bd58bcba407446b5d0d75e0e1c
_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
#
#NelmioApiDocBundle:
#    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
#    prefix: "/doc"


#api:
#    type: rest
#    resource: "routing_api.yml"
#
#list:
#    path: /
#    defaults: {_controller: AppBundle:Project:list}
#
#project_create:
#    path:     /project/create
#    defaults: { _controller: AppBundle:Project:create }
#
#project_edit:
#    resource: "@AppBundle/Controller"
#    type:     annotation
#    defaults: { _controller: AppBundle:Project:edit }