# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    my.twig.extension:
        class: AppBundle\Twig\LocalizedPath
        arguments: [ "@service_container" ]
        tags:
           - { name: twig.extension }
    listener.requestresponse:
        class: AppBundle\EventListener\KernelListener
        arguments: [ "@service_container" ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    doctrine_entity_repository.application:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Application
    doctrine_entity_repository.project:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Project
    doctrine_entity_repository.person:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Person
    doctrine_entity_repository.person_contact:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\PersonContact
    doctrine_entity_repository.institution:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Institution
    doctrine_entity_repository.program:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Program
    doctrine_entity_repository.picNumber:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\PicNumber
    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true
    app.doctrine.hash_password_listener:
        class: AppBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }