# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    my.twig.extension:
        class: AppBundle\Twig\LocalizedPath
        arguments: [ "@service_container" ]
        tags:
           - { name: twig.extension }
    listener.requestresponse:
        class: AppBundle\EventListener\KernelListener
        arguments: [ "@service_container" ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    doctrine_entity_repository.application:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Application
    doctrine_entity_repository.projects:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Projects
    doctrine_entity_repository.persons:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Persons
    doctrine_entity_repository.person_contacts:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\PersonContacts
    doctrine_entity_repository.institutions:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Institutions
    doctrine_entity_repository.program:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Program