# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
parameters:
    my.file_type_extension.class: AppBundle\FormType\FileTypeExtension

services:
    my.twig.extension:
        class: AppBundle\Twig\LocalizedPath
        arguments: [ "@service_container" ]
        tags:
           - { name: twig.extension }
    my.twig.extension.active_route:
        class: AppBundle\Twig\ActiveRoute
        arguments: [ "@service_container" ]
        tags:
           - { name: twig.extension }
    listener.requestresponse:
        class: AppBundle\EventListener\KernelListener
        arguments: [ "@service_container" ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    util.file_uploader:
        class: AppBundle\Util\FileUploader
        arguments: ["%file_uploads_directory%"]
    get_set_method_normalizer:
      class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
      public: false
      tags:
        - { name: serializer.normalizer }

    my.file_type_extension:
      class: %my.file_type_extension.class%
      tags:
        - { name: form.type_extension, alias: file, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }

    doctrine_entity_repository.application:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Application
    doctrine_entity_repository.project:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Project
    doctrine_entity_repository.person:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Person
    doctrine_entity_repository.person_contact:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\PersonContact
    doctrine_entity_repository.person_address:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\PersonAddress
    doctrine_entity_repository.person_note:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\PersonNote
    doctrine_entity_repository.person_note_type:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\PersonNoteType
    doctrine_entity_repository.person_document_type:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\PersonDocumentType
    doctrine_entity_repository.person_document:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\PersonDocument
    doctrine_entity_repository.institution:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Institution
    doctrine_entity_repository.person_institution_relationship_type:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\PersonInstitutionRelationshipType
    doctrine_entity_repository.person_institution_relationship:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\PersonInstitutionRelationship
    doctrine_entity_repository.person_field_of_expertise:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\PersonFieldOfExpertise
    doctrine_entity_repository.field_of_expertise:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\FieldOfExpertise
    doctrine_entity_repository.facing_situation:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\FacingSituation
    doctrine_entity_repository.person_facing_situation:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\PersonFacingSituation
    doctrine_entity_repository.institution_type:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\InstitutionType
    doctrine_entity_repository.institution_contact:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\InstitutionContact
    doctrine_entity_repository.institution_note_type:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\InstitutionNoteType
    doctrine_entity_repository.institution_note:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\InstitutionNote
    doctrine_entity_repository.institution_accreditation_type:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\InstitutionAccreditationType
    doctrine_entity_repository.institution_accreditation:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\InstitutionAccreditation
    doctrine_entity_repository.institution_address:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\InstitutionAddress
    doctrine_entity_repository.institution_founder_type:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\InstitutionFounderType
    doctrine_entity_repository.institution_level:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\InstitutionLevel
    doctrine_entity_repository.institution_legal_representative:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\InstitutionLegalRepresentative
    doctrine_entity_repository.program:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Program
    doctrine_entity_repository.pic_number:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\PicNumber
    doctrine_entity_repository.contact_type:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ContactType
    doctrine_entity_repository.project_applicant_organisation:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ProjectApplicantOrganisation
    doctrine_entity_repository.project_key_action:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ProjectKeyAction
    doctrine_entity_repository.project_action:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ProjectAction
    doctrine_entity_repository.project_partner_organisation:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ProjectPartnerOrganisation
    doctrine_entity_repository.project_call:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ProjectCall
    doctrine_entity_repository.project_round:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ProjectRound
    doctrine_entity_repository.project_contact_persons:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ProjectContactPerson
    doctrine_entity_repository.project_topics:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ProjectTopic
    doctrine_entity_repository.project_subject_areas:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ProjectSubjectArea
    doctrine_entity_repository.project_limitation:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ProjectLimitation
    doctrine_entity_repository.project_notes:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ProjectNote
    doctrine_entity_repository.project_target_group:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ProjectTargetGroup
    doctrine_entity_repository.project_target_group_fewer_opportunities:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ProjectTargetGroupFewerOpportunities
    doctrine_entity_repository.project_priority:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ProjectPriority
    doctrine_entity_repository.project_contact:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ProjectContact
    doctrine_entity_repository.project_evaluator_grade:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ProjectEvaluatorGrade
    doctrine_entity_repository.activity:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Activity
    doctrine_entity_repository.action_details:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ActionDetails
    doctrine_entity_repository.resources:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Resources
    doctrine_entity_repository.project_resources:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ProjectResources
    doctrine_entity_repository.project_results:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ProjectResults
    doctrine_entity_repository.results:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Results
    doctrine_entity_repository.institution_risk_level:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\InstitutionRiskLevel
    doctrine_entity_repository.institution_risk_level_type:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\InstitutionRiskLevelType
    doctrine_entity_repository.equipment_risk_level:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\EquipmentRiskLevel
    doctrine_entity_repository.file:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\File
    doctrine_entity_repository.project_equipment:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ProjectEquipment
    doctrine_entity_repository.equipment_type:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\EquipmentType
    doctrine_entity_repository.equipment:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Equipment
    doctrine_entity_repository.project_intelectual_outputs:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ProjectIntelectualOutputs
    doctrine_entity_repository.intelectual_outputs:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\IntelectualOutputs
    doctrine_entity_repository.project_reporting:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ProjectReporting
    doctrine_entity_repository.reporting:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Reporting
    doctrine_entity_repository.reporting_person:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ReportingPerson
    doctrine_entity_repository.reporting_questions_and_answers:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ReportingQuestionsAndAnswers
    doctrine_entity_repository.project_deliverables_activities:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ProjectDeliverablesActivities
    doctrine_entity_repository.project_activities:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ProjectActivity
    doctrine_entity_repository.project_deliverables:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ProjectDeliverable
    doctrine_entity_repository.questions:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Questions
    doctrine_entity_repository.project_monitoring_reporting:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ProjectMonitoringReporting
    doctrine_entity_repository.monitoring_reporting:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\MonitoringReporting
    doctrine_entity_repository.project_partners:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ProjectPartners
    doctrine_entity_repository.partners:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Partners
    doctrine_entity_repository.partners_team_members:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\PartnersTeamMembers
    doctrine_entity_repository.partners_participants:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\PartnersParticipants
    doctrine_entity_repository.attachments:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Attachments
    doctrine_entity_repository.attachments_dms_documents:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\AttachmentsDmsDocuments
    doctrine_entity_repository.attachments_manually_uploaded:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\AttachmentsManuallyUploaded
    doctrine_entity_repository.group_calendar:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\GroupCalendar
    doctrine_entity_repository.group_calendar_event:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\GroupCalendarEvent
    doctrine_entity_repository.event_reminder:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\EventReminder
    doctrine_entity_repository.user_permission:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\UserPermission
    doctrine_entity_repository.existing_project_permission:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ExistingProjectPermission
    doctrine_entity_repository.existing_institution_permission:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ExistingInstitutionPermission
    doctrine_entity_repository.project_mobility_flows:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ProjectMobilityFlows
    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true
    app.doctrine.hash_password_listener:
        class: AppBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }